name: Export PPK Store as Artifact

on:
  workflow_dispatch: {}

permissions:
  contents: read


jobs:
  export-ppk-store:
    env:
      PPK_STORE: ${{ secrets.PPK_STORE }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up repository
        uses: actions/checkout@v4

      - name: Decode PPK_STORE secret and save to file
        run: |
          echo "${{ env.PPK_STORE }}" | base64 -d > ppk_store.json

      - name: Upload ppk_store.json as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ppk_store
          path: ppk_store.json
