name: Update README on Package Changes

on:
  push:
    branches: [develop, main]
    paths:
      - 'packages/**/package.json'
      - 'packages/**/.releaseconfig.json'
  pull_request:
    branches: [develop, main]
    paths:
      - 'packages/**/package.json'
      - 'packages/**/.releaseconfig.json'

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.PAT_FOR_PACKAGES }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Update README
        run: pnpm update-readme

      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit README changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add readme.md
          git commit -m "docs: auto-update README package list

          📦 Updated package information in README.md
          - Synced package versions and descriptions
          - Updated artifact links

          Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"

      - name: Push changes
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'push'
        run: git push

      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true' && github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:auto-update-readme-${{ github.event.number }}
          gh pr create \
            --base ${{ github.head_ref || github.ref_name }} \
            --head auto-update-readme-${{ github.event.number }} \
            --title "docs: auto-update README package list" \
            --body "## 📦 Auto-generated README Update

          This PR was automatically created to update the README.md package list.

          ### Changes
          - ✅ Updated package versions and descriptions
          - ✅ Synced artifact download links
          - ✅ Added new packages (if any)

          ### Generated by
          - GitHub Actions workflow
          - Triggered by package.json changes in: ${{ github.event.pull_request.head.sha || github.sha }}

          This update ensures the README stays in sync with the actual packages in the repository."